#
# ███████╗░██████╗░██████╗███████╗███╗░░██╗░█████╗░███████╗        ██████╗░███████╗██╗░░░██╗
# ██╔════╝██╔════╝██╔════╝██╔════╝████╗░██║██╔══██╗██╔════╝        ██╔══██╗██╔════╝██║░░░██║
# █████╗░░╚█████╗░╚█████╗░█████╗░░██╔██╗██║██║░░╚═╝█████╗░░        ██║░░██║█████╗░░╚██╗░██╔╝
# ██╔══╝░░░╚═══██╗░╚═══██╗██╔══╝░░██║╚████║██║░░██╗██╔══╝░░        ██║░░██║██╔══╝░░░╚████╔╝░
# ███████╗██████╔╝██████╔╝███████╗██║░╚███║╚█████╔╝███████╗        ██████╔╝███████╗░░╚██╔╝░░
# ╚══════╝╚═════╝░╚═════╝░╚══════╝╚═╝░░╚══╝░╚════╝░╚══════╝        ╚═════╝░╚══════╝░░░╚═╝░░░
#
# Связь с разработчиком плагина:
# ds: javaessence
# tg: EsnJava
#



# Enable/disable the title and subtitle | Включение/выключение Title и SubTitle
EnableTitle: true


# Customizing text after revival | Настройка текста после возрождения
Title: "§cВы погибли :("
Subtitle: "§aВоскресье!"


# Setting Title and SubTitle | Настройка Title и SubTitle
TitleFadeIn: 10
TitleStay: 40
TitleFadeOut: 10


# Sound after revival | Звук после возрождения
Sound: ENTITY_PLAYER_LEVELUP


